### ISSUE TITLE
Header.rewite() failure with long strings

### ISSUE THREAD

**Issue by nasamaher** [nom-tam-fits/nom-tam-fits#46]
Using git HEAD from 8/14/15 (with long strings and HIERACH fix), I moved forward with my development.  I stumbled on a problem when using long strings in combination with HIERARCH.  After reading a nom-tam-fits generated FITS file with a certain combination of long strings & HIERARCH - and without changing anything in the header - I can't rewrite() the header.  It seems that in this situation that Header.rewritable() thinks that getNumberOfPhysicalCards() differs significantly from this.originalCardCount.   The following code fails with this file:

```java
		FitsFactory.setUseHierarch(true);
		FitsFactory.setLongStringsEnabled(true);

		String filename = "test.fits";
		Header headerRewriter = new Fits(filename).getHDU(0).getHeader();
		headerRewriter.rewrite();
```

Since I can't attach the file  ("test.fits" here, I have put it on a public drive:

https://opendrive.gsfc.nasa.gov/longauth/x/FmcJXoC 

Steve

**Comment by ritchieGitHub** [comment]
I think this is a folow-up error from my #44 fix, clearly I have some missing unit tests. I will try to fix this tomottow.

**Comment by ritchieGitHub** [comment]
@nasamaher I will pospone the realease to next weekend so you have more time "detecting" bugs. in this (till now) few used combination of features.

**Comment by ritchieGitHub** [comment]
@nasamaher it is fixed, it was a very old nasty bug ;-) nothing to do with #44 . I included your file as a unit test, if that is not ok please write it here. I think rewriting is not a much used feature ;-)

**Comment by nasamaher** [comment]
Thank you for the effort!  Using the file in unit tests is fine.  I will
run tests on Monday.

I do rewrites because we are streaming large data into a binary table and
we get some of our header information *after *we start writing the binary
table.  So when I first create the FITS file I create a header with all the
keys (but dummy data) and then rewrite the keys and header when I have the
real values.

If there's a better way to do this then let me know!

Thanks again,
Steve

**Comment by nasamaher** [comment]
I've realized that creating a header with dummy data will still not work as any significant size deviation from the dummy data will make a header non-rewriteable.  So now I am adding a "Padding" keyword with enough size so that I can remove (or add) to it to keep the header size within the 35? card size (i.e., keep it rewritable)

**Comment by ritchieGitHub** [comment]
@TomMcGlynn should we include some api to allow controll of the padding? something like
```
header.paddingCards(nrOfCards);
```
(would only be used during write and not during rewrite)

**Comment by nasamaher** [comment]
FYI, the bug fix works great (thanks!) and now I've implemented a method to adjust header padding (as described above) and it's working great.  Our case is kind of extreme - I need a padding of roughly 500K in order to deal with size changes (up or down).  A later stage in our system will remove the padding header value as it re-processes the FITS file.  

I now have data streaming to a binary table and can rewrite the header at will. Very flexible!

At least for the time being I have completed all my tests for nom.tam.  Thanks so much for maintaining this very useful project!

Steve


Note, this method assumes HEADER_PADDING_KEYWORD already written to header ...

```java
    /**
     * Increase or decrease length of HEADER_PADDING_KEYWORD in order to make
     * the header rewritable.
     * 
     * @param header
     * @throws HeaderCardException
     */
    private void adjustHeaderPaddingToMakeRewritable(Header header)
            throws HeaderCardException
    {
        if (header.rewriteable() == false)
        {
            /*
             * First try the exact byte difference needed, but this will not be
             * correct because of the additional "CONTINUE" keywords and line
             * continuation characters ('&'). So follow this with an iterative
             * method of changing length by a Fits block size until we are
             * declared rewritable()
             */
            long size = header.getSize();
            long originalSize = header.getOriginalSize();
            long delta = originalSize - size;
            int newPaddingSize = (int) (header.getStringValue(
                    HEADER_PADDING_KEYWORD).length() + delta);

            int ct = 0;
            while (header.rewriteable() == false)
            {
                if (++ct % 5 == 0)
                {
                    sLogger.logp(Level.SEVERE, "MceFitsArchiver",
                            "adjustHeaderPadding(Header)",
                            "Not iterating to Header Padding solution");
                }
                size = header.getSize();
                originalSize = header.getOriginalSize();

                if (originalSize > size)
                {
                    newPaddingSize += FitsFactory.FITS_BLOCK_SIZE;
                }
                else
                {
                    newPaddingSize -= FitsFactory.FITS_BLOCK_SIZE;
                }

                if (newPaddingSize < 1)
                {
                    sLogger.logp(Level.SEVERE, "MceFitsArchiver",
                            "adjustHeaderPaddingToMakeRewritable(Header)",
                            "Not enough padding to adjust for new size!");
                    return;
                }
                char[] newPadArray = new char[newPaddingSize];
                Arrays.fill(newPadArray, 'F');
                header.addValue(HEADER_PADDING_KEYWORD,
                        new String(newPadArray), "for header resize");
            }
        }
    }
```
