### ISSUE TITLE
Not correctly verifying checksums

### ISSUE THREAD

**Issue by tony-johnson** [nom-tam-fits/nom-tam-fits#473]
HI, either I am doing something very wrong, or there is something wrong with the checksum computation code in nom.tam.fits. I did the following:

1) Downloaded this file http://fits.gsfc.nasa.gov/registry/checksum/checksum.fits
2) Used astropy fitscheck to verify the checksums are correct.
3) Took the following example code from https://github.com/nom-tam-fits/nom-tam-fits#checksums

```java
    public static void main(String[] args) throws IOException, FitsException {
        Fits fits = new Fits("/home/tonyj/Data/checksum.fits");
        BasicHDU<?> hdu = fits.readHDU();
        if (fits.calcChecksum(0) != hdu.getStoredChecksum()) {
            System.err.println("WARNING! The HDU might be corrupted.");
        }
     }
```

4) Run it, and see:
WARNING! The HDU might be corrupted.

**Comment by attipaci** [comment]
Hi @tony-johnson,

I did take a quick look. It looks like the DATASUM agrees for both HDU 0 and HDU 1, and its only the full checksum (including the header) which differs. That indicates that the issue is calculating the checksum of the header... I'll investigate some more...

**Comment by attipaci** [comment]
@tony-johnson,

Update, I found the culprit. The original header has a number of blank cards before the END keyword, which get discarded on reading as part of treating them as reserved header space. This is why the checksum differs. This should be relatively easy to fix. I'll let you know when something is available for testing.

**Comment by attipaci** [comment]
@tony-johnson, 

I've created a path in PR #474. This adds new `Fits.verifyIntegrity()`, `Fits.verifyIntegrity(int)` and `Fits.verifyDataIntegrity(int)` methods that can be used to check the integrity of exisiting FITS files _as they are written_ (rather than as nom-tam-fits would write them). I've also updated the README. Feel free to check it out, and provide any feedback. In the meantime, I'll work on adding test cases to all the code that has been added. I plan to merge the PR next week and create a new 1.18.1 release candidate with it.

**Comment by tony-johnson** [comment]
HI, thanks for the quick fix. The new verifyIntegrity() method works for the sample file I mentioned in the original post. It seems to make some assumptions about random access which do not work for the compressed files I was originally wanting to test, but I will look to see if I can work around that.

**Comment by attipaci** [comment]
@tony-johnson,

Yes, non random access is a bit tricky, since you cannot go back to the file again once it was read. We could rewrite it (e.g. to a ByteBufferOutputStream) for the checksum calculation, but then there is no assurance that the way we'd write the header/data would be byte-for-byte the same as the original stream -- which was part of the problem with the checksum verification in the first place... 

The only way I see doing check-sum verification for streams (i.e. non random access inputs) is to calculate the checksum when reading HDUs. But, this would impact performance if it was always turned on, and no checksum verification is required -- which is why I'd be hesitant to go down that road...

Maybe, we can set an option in the `Fits` instance before `read()` or `readHDU()` calls that would enable automatic checksum verification on successive read calls, something like:

```java
  Fits fits = ...

  // We'll automatically verify checksums for HDUs we read. If the verification fails we throw an exception
  fits.setVerifyChecksumsWheanReading(true);

  try {
      fits.readHDU(0);
  } catch (FitsIntegrityException e) {
      // The checksum or datasum did not match
  } catch (...) {
     ...
  }
```

Here `FitsIntegrityException` would be a subclass of `FitsException` so it would be 100% back compatible.

**Comment by attipaci** [comment]
Hi @tony-johnson,

I merged the first PR, and created a new one: PR #478, which adds automatics checksumming to `FitsInputStream`s. No extra switches are used, and so verification ise performed the same way as for random-access files. It turns out that the extra calculation does not seem to affect performance at all (definitely not significantly), so I think we might call it a day.

Please take it for a spin and let me know if it works for your use case, of if there is need for further tweaks...

**Comment by tony-johnson** [comment]
HI, I am testing this now, but for my (LSST) compressed FITS files the header verification is still not working, if I am understanding how to use it. Basically:

        Fits fits = new Fits("/home/tonyj/Data/checksum.fits");
        fits.verifyIntegrity();

works, but:

        Fits fits = new Fits("/home/tonyj/Data/MC_C_20230625_001140_R22_S10.fits");
        fits.verifyIntegrity();

fails with:

Exception in thread "main" nom.tam.fits.FitsException: Corrupted HDU[0]
	at nom.tam.fits.Fits.verifyIntegrity(Fits.java:1205)
	at org.lsst.fitsverify.Main.main(Main.java:20)
Caused by: nom.tam.fits.FitsIntegrityException: Failed checksum: got 0, expected 4294967295
	at nom.tam.fits.BasicHDU.verifyIntegrity(BasicHDU.java:638)
	at nom.tam.fits.Fits.verifyIntegrity(Fits.java:1203)

Note that fitsverify on that file works. If you have time to look the file I used can be downloaded here:

https://www.dropbox.com/scl/fi/ypkzuu0w161ebw0hmy22r/MC_C_20230625_001140_R22_S10.fits?rlkey=d8wpwllo6bzmxdo9hfth18pus&dl=0

**Comment by tony-johnson** [comment]
I should add a little background on why I am trying to make this work (instead of just using fitsverify). My goal is to have an implementation of nom.tam.util.RandomAccess which allows me to read FITS files directly from an s3 file system, and to then be able to verify the checksums/datasums on the files directly from there.

**Comment by attipaci** [comment]
@tony-johnson,

Sorry about that. It was all because of a silly corner case of `NullData`, affecting HDUs that contain only headers but no data segment. That is why it slipped through the tests. I have committed the 1-line fix to `NullData` to master at 01409302f6cb2cef9dbb8f7d3446c03bfc8a30e2. Hopefully that will do the trick. 

Let me know if you run into any other problems. I plan to release 1.18.1 around 9/15, so hopefully we can get this sorted completely before then :-). Thanks for your help!

**Comment by attipaci** [comment]
For an even better (but functionally equivalent) fix, I have created a new PR #479. It should avoid divergent `Data` classes messing up verification, and result in a more foolproof way of getting to the same end result.
